name: SongPlug
version: '1.0-SNAPSHOT'
main: net.mrbeelo.songPlug.SongPlug
api-version: '1.21'
commands:
  class:
    description: Opens a menu for the player to change their class
  givesong:
    description: Gives the player the specified song
  getblock:
    description: Gets the block the entity is standing on
  resetcooldowns:
    description: Resets all ardoni song cooldowns
  energy:
    description: Sets the ardoni song energy amount
  infusesong:
    description: Infuses the specified song onto the player
  clearsongs:
    description: Clears the player's songs
  level:
    description: Sets the player's level
  sowxp:
    description: Sets the player's xp
  skull:
    description: Sets the player's skull
  weapontype:
    description: Sets the held weapon's type